#!/usr/bin/env bash
# Parse the actual bundled themes with native Arch binaries, without a display.
# This intentionally uses a disposable HOME and does not run the installer.
set -euo pipefail
umask 077

[[ "$(uname -s)" == Linux ]] || { printf 'Native validation requires Linux.\n' >&2; exit 1; }
[[ "$(id -u)" != 0 ]] || { printf 'Run native validation as an unprivileged user.\n' >&2; exit 1; }
for program in Hyprland fuzzel luac; do
    command -v "$program" >/dev/null || { printf 'Missing native validator: %s\n' "$program" >&2; exit 1; }
done

SOURCE=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd -P)
NATIVE_HOME=$(mktemp -d /tmp/arian-hypr-native.XXXXXX)
cleanup() {
    # NATIVE_HOME is generated by mktemp, never a caller-provided directory.
    [[ "$NATIVE_HOME" == /tmp/arian-hypr-native.* ]] && rm -rf -- "$NATIVE_HOME"
}
trap cleanup EXIT
NATIVE_CONFIG="$NATIVE_HOME/.config"
NATIVE_STATE="$NATIVE_HOME/.local/state"
NATIVE_CACHE="$NATIVE_HOME/.cache"
NATIVE_RUNTIME="$NATIVE_HOME/runtime"
native() {
    # Only the parser subprocess receives the disposable desktop environment.
    env -u WAYLAND_DISPLAY -u DISPLAY -u HYPRLAND_INSTANCE_SIGNATURE \
        HOME="$NATIVE_HOME" XDG_CONFIG_HOME="$NATIVE_CONFIG" \
        XDG_STATE_HOME="$NATIVE_STATE" XDG_CACHE_HOME="$NATIVE_CACHE" \
        XDG_RUNTIME_DIR="$NATIVE_RUNTIME" "$@"
}
mkdir -p -- "$NATIVE_CONFIG/arian-hypr-local" "$NATIVE_RUNTIME" "$NATIVE_STATE" "$NATIVE_CACHE"
cp -a -- "$SOURCE/config/hypr" "$SOURCE/config/arian-hypr" "$NATIVE_CONFIG/"
printf '%s\n' '-- Empty personal overrides for isolated native validation.' > "$NATIVE_CONFIG/arian-hypr-local/local.lua"
printf '%s\n' '# Empty personal overrides for isolated native validation.' > "$NATIVE_CONFIG/arian-hypr-local/local.conf"

native Hyprland --version
native fuzzel --version
while IFS= read -r -d '' file; do
    luac -p "$file"
done < <(find "$NATIVE_CONFIG" -type f -name '*.lua' -print0)

for theme in frost haunt; do
    printf '\nChecking native parsers with the %s theme\n' "$theme"
    ln -sfn -- "themes/$theme" "$NATIVE_CONFIG/arian-hypr/current"
    # Hyprland's verify-config mode returns before compositor/server creation.
    # This exercises the actual Lua API and theme file, not a stand-in parser.
    native Hyprland --verify-config --config "$NATIVE_CONFIG/hypr/hyprland.lua"
    # Arch's fuzzel(1) documents a display-free check with exit code 0/1:
    # https://man.archlinux.org/man/fuzzel.1.en
    native fuzzel --check-config --config "$NATIVE_CONFIG/arian-hypr/current/fuzzel.ini"
done

printf '\nBoth themes passed native Hyprland Lua and Fuzzel configuration validation.\n'
