font=JetBrainsMono Nerd Font 11
background-color=#111b27f5
text-color=#e3f3ff
border-color=#30475a
border-size=1
border-radius=14
width=320
height=140
padding=16
outer-margin=62,16,0
margin=6
anchor=top-right
default-timeout=6000
max-visible=4
max-history=30
icons=1
max-icon-size=40
on-button-left=invoke-default-action
on-button-right=dismiss

[urgency=critical]
border-color=#ff8c9a
default-timeout=0

[mode=do-not-disturb]
invisible=1
