#!/usr/bin/env python3
"""Rebuild the two original desktop palettes. No dependencies or network access."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
BUNDLE = ROOT / "config/arian-hypr"
ACTION = "$HOME/.config/arian-hypr/scripts/actions.sh"
THEME = "$HOME/.config/arian-hypr/scripts/theme.sh"
PALETTES = {
    "frost": dict(name="FROST", icon="❄", subtitle="Quiet hours. Clear mind.",
                  bg="0b1018", panel="111b27", raised="1c2d3e", text="e3f3ff",
                  muted="9db3c6", accent="8edbff", second="b5bcff", line="30475a",
                  red="ff8c9a", green="a5dfbd", yellow="efd4a0", workspace=["1", "2", "3", "4", "5"]),
    "haunt": dict(name="HAUNT", icon="🎃", subtitle="A little midnight mischief.",
                  bg="100d17", panel="1b1426", raised="35203f", text="f6e9ff",
                  muted="bd9ccc", accent="ffa45c", second="c69aff", line="51325f",
                  red="ff8295", green="b8d98a", yellow="ffd089", workspace=["🎃", "👻", "🦇", "🕸", "🌙"]),
}


def write(path, content):
    path.write_text(content.strip() + "\n")


def build(slug, p):
    dest = BUNDLE / "themes" / slug
    dest.mkdir(parents=True, exist_ok=True)
    write(dest / "palette.json", json.dumps(p, indent=2, ensure_ascii=False))
    bar = {
        "layer": "top", "position": "top", "height": 40, "spacing": 0,
        "margin-top": 12, "margin-left": 16, "margin-right": 16, "margin-bottom": 0,
        # Stable Waybar's native workspace clicks use removed legacy IPC on Lua.
        "modules-left": ["custom/brand"] + [f"custom/workspace{i}" for i in range(1, 6)],
        "modules-center": ["clock"],
        "modules-right": ["idle_inhibitor", "pulseaudio", "network", "custom/control", "custom/theme", "custom/power"],
        "custom/brand": {"format": p["icon"] + "  " + p["name"], "tooltip-format": "Open applications · Super + Space", "on-click": ACTION + " launcher", "on-click-right": ACTION + " help"},
        "clock": {"format": "{:%a  %H:%M}", "format-alt": "{:%d %B %Y}",
                  "tooltip-format": "<big>{:%B %Y}</big>\n<tt><small>{calendar}</small></tt>"},
        "idle_inhibitor": {"format": "{icon}", "format-icons": {"activated": "󰅶", "deactivated": "󰾪"},
                           "tooltip-format-activated": "Keep awake · click to allow idle lock", "tooltip-format-deactivated": "Idle lock enabled · click to keep awake"},
        "pulseaudio": {"format": "{icon} {volume}%", "format-muted": "󰖁 Muted", "format-icons": {"default": ["󰕿", "󰖀", "󰕾"]}, "scroll-step": 3, "on-click": "pavucontrol", "on-click-right": "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle", "tooltip-format": "{desc}"},
        "network": {"format-wifi": "󰖩", "format-ethernet": "󰈀", "format-disconnected": "󰖪", "tooltip-format": "{ifname} · {ipaddr}", "on-click": ACTION + " network"},
        "custom/control": {"format": "󰒓", "tooltip-format": "Control room · audio, network, notifications, clipboard", "on-click": ACTION + " settings", "on-click-right": ACTION + " help"},
        "custom/theme": {"format": "👻" if slug == "haunt" else "❅", "tooltip-format": "Switch Frost / Haunt · Super + Shift + T", "on-click": THEME + " toggle"},
        "custom/power": {"format": "⏻", "tooltip-format": "Session menu", "on-click": ACTION + " power"},
    }
    for i in range(1, 6):
        bar[f"custom/workspace{i}"] = {
            "exec": f"{ACTION} workspace-status {i}", "return-type": "json",
            "interval": 2, "format": "{text}", "exec-on-event": True,
            "on-click": f"{ACTION} workspace {i}", "escape": True,
        }
    write(dest / "waybar.json", json.dumps(bar, indent=2, ensure_ascii=False))
    write(dest / "waybar.css", f"""
/* Generated by tools/build_themes.py. GTK CSS, not browser CSS. */
* {{ font-family: "JetBrainsMono Nerd Font", "Noto Color Emoji", monospace; font-size: 12px; min-height: 0; border: none; }}
window#waybar {{ background: transparent; color: #{p['text']}; }}
.modules-left, .modules-center, .modules-right {{ background: alpha(#{p['panel']}, 0.97); border: 1px solid #{p['line']}; border-radius: 14px; }}
.modules-left {{ padding: 0 6px 0 0; }}
.modules-center {{ padding: 0 20px; }}
.modules-right {{ padding: 0 4px; }}
#custom-brand {{ color: #{p['accent']}; font-weight: bold; padding: 0 16px; margin-right: 3px; border-right: 1px solid #{p['line']}; }}
#custom-workspace1, #custom-workspace2, #custom-workspace3, #custom-workspace4, #custom-workspace5 {{ color: #{p['muted']}; background: transparent; padding: 0 9px; margin: 4px 2px; border-radius: 8px; min-width: 16px; }}
#custom-workspace1.active, #custom-workspace2.active, #custom-workspace3.active, #custom-workspace4.active, #custom-workspace5.active {{ color: #{p['bg']}; background: #{p['accent']}; font-weight: bold; }}
#custom-workspace1:hover, #custom-workspace2:hover, #custom-workspace3:hover, #custom-workspace4:hover, #custom-workspace5:hover {{ background: #{p['raised']}; color: #{p['text']}; }}
#clock {{ font-weight: bold; color: #{p['text']}; }}
#idle_inhibitor, #pulseaudio, #network, #custom-control, #custom-theme, #custom-power {{ padding: 0 10px; color: #{p['muted']}; border-radius: 10px; margin: 3px 0; }}
#custom-theme {{ color: #{p['second']}; font-size: 16px; }}
#custom-power {{ color: #{p['accent']}; padding-right: 12px; }}
#idle_inhibitor.activated {{ color: #{p['accent']}; }}
#pulseaudio:hover, #network:hover, #custom-control:hover, #custom-theme:hover, #custom-power:hover {{ background: #{p['raised']}; color: #{p['text']}; }}
tooltip {{ background: #{p['panel']}; border: 1px solid #{p['line']}; border-radius: 12px; }}
tooltip label {{ color: #{p['text']}; padding: 10px; }}
""")
    write(dest / "fuzzel.ini", f"""
[main]
font=JetBrainsMono Nerd Font:size=12,Noto Color Emoji:size=12
dpi-aware=no
prompt="{p['icon']}  "
icon-theme=Papirus-Dark
icons-enabled=yes
terminal=kitty -e
lines=8
width=38
horizontal-pad=24
vertical-pad=20
inner-pad=12
line-height=30
layer=overlay

[colors]
background={p['panel']}fa
text={p['text']}ff
match={p['accent']}ff
selection={p['raised']}ff
selection-text={p['text']}ff
selection-match={p['accent']}ff
border={p['second']}cc
prompt={p['accent']}ff

[border]
width=2
radius=18
""")
    write(dest / "mako.conf", f"""
font=JetBrainsMono Nerd Font 11
background-color=#{p['panel']}f5
text-color=#{p['text']}
border-color=#{p['line']}
border-size=1
border-radius=14
width=320
height=140
padding=16
outer-margin=62,16,0
margin=6
anchor=top-right
default-timeout=6000
max-visible=4
max-history=30
icons=1
max-icon-size=40
on-button-left=invoke-default-action
on-button-right=dismiss

[urgency=critical]
border-color=#{p['red']}
default-timeout=0

[mode=do-not-disturb]
invisible=1
""")
    write(dest / "kitty.conf", f"""
# {p['name']} — terminal palette. Included by the shared kitty.conf.
foreground #{p['text']}
background #{p['bg']}
selection_foreground #{p['bg']}
selection_background #{p['accent']}
cursor #{p['accent']}
cursor_text_color #{p['bg']}
url_color #{p['second']}
active_border_color #{p['accent']}
inactive_border_color #{p['line']}
active_tab_foreground #{p['bg']}
active_tab_background #{p['accent']}
inactive_tab_foreground #{p['muted']}
inactive_tab_background #{p['panel']}
tab_bar_background #{p['bg']}
color0 #{p['panel']}
color1 #{p['red']}
color2 #{p['green']}
color3 #{p['yellow']}
color4 #{p['accent']}
color5 #{p['second']}
color6 #{p['accent']}
color7 #{p['text']}
color8 #{p['muted']}
color9 #{p['red']}
color10 #{p['green']}
color11 #{p['yellow']}
color12 #{p['accent']}
color13 #{p['second']}
color14 #{p['accent']}
color15 #ffffff
""")
    write(dest / "hyprland.conf", f"""
# {p['name']} palette for Hyprland 0.54.
general {{
    col.active_border = rgba({p['accent']}ff) rgba({p['second']}ff) 45deg
    col.inactive_border = rgba({p['line']}ff)
}}
""")
    write(dest / "hyprland.lua", f"""
-- {p['name']} palette for Hyprland 0.55+.
hl.config({{
    general = {{
        col = {{
            active_border = {{colors = {{"rgba({p['accent']}ff)", "rgba({p['second']}ff)"}}, angle = 45}},
            inactive_border = "rgba({p['line']}ff)",
        }},
    }},
}})
""")
    write(dest / "hyprlock.conf", f"""
# Original {p['name']} lock screen. Uses your Linux account password.
general {{
    hide_cursor = true
}}
background {{
    monitor =
    path = ~/.config/arian-hypr/current/wallpaper.png
    color = rgb({p['bg']})
    blur_passes = 0
    brightness = 0.55
}}
label {{
    monitor =
    text = {p['icon']}  {p['name']}
    color = rgb({p['accent']})
    font_size = 18
    font_family = JetBrainsMono Nerd Font
    position = 0, 190
    halign = center
    valign = center
}}
label {{
    monitor =
    text = $TIME
    color = rgb({p['text']})
    font_size = 76
    font_family = JetBrainsMono Nerd Font
    position = 0, 80
    halign = center
    valign = center
}}
label {{
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"
    color = rgb({p['muted']})
    font_size = 14
    font_family = JetBrainsMono Nerd Font
    position = 0, 10
    halign = center
    valign = center
}}
input-field {{
    monitor =
    size = 290, 52
    outline_thickness = 2
    dots_size = 0.22
    dots_spacing = 0.25
    outer_color = rgb({p['accent']}) rgb({p['second']}) 45deg
    inner_color = rgb({p['panel']})
    font_color = rgb({p['text']})
    check_color = rgb({p['second']})
    fail_color = rgb({p['red']})
    font_family = JetBrainsMono Nerd Font
    placeholder_text = <span foreground="#{p['muted']}">Enter password</span>
    fail_text = Try again
    fade_on_empty = false
    rounding = 14
    position = 0, -80
    halign = center
    valign = center
}}
label {{
    monitor =
    text = {p['subtitle']}
    color = rgb({p['muted']})
    font_size = 12
    font_family = JetBrainsMono Nerd Font
    position = 0, 40
    halign = center
    valign = bottom
}}
""")


if __name__ == "__main__":
    for name, palette in PALETTES.items():
        build(name, palette)
    print("Rebuilt Frost and Haunt configurations; wallpapers preserved.")
